[project]
name = "sqlens"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "sqlfluff>=4.2.2",
    "sqruff>=0.39.0",
    "ruff>=0.15.20",
    "ty>=0.0.56",
]

[tool.uv]
compile-bytecode = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "COM812",
    "D101",
    "D103",
    "D203",
    "D213",
    "EM102",
    "S603",
    "T201",
    "TRY003",
]

[tool.ruff.format]
# Respecting the official example of ruff: https://docs.astral.sh/ruff/configuration/
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
